# Generated by Django 5.1.3 on 2024-11-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_nota_trimestre"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="curso",
            name="disciplina",
        ),
        migrations.AddField(
            model_name="ocorrencia",
            name="data_ocorrencia",
            field=models.IntegerField(default=2024),
        ),
        migrations.AddField(
            model_name="ocorrencia",
            name="trimestre",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "1º Trimestre"), (2, "2º Trimestre"), (3, "3º Trimestre")],
                default=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="turma",
            name="disciplina",
            field=models.ManyToManyField(blank=True, to="core.disciplina"),
        ),
    ]
